name: wildscan_report_app
description: "Professional Wildlife Crime Reporting App for Hackathon 2026."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10+1
  http: ^1.1.0
  geolocator: ^10.1.0
  exif: ^3.1.5
  geocoding: ^3.0.0
  permission_handler: ^12.0.1
  video_player: ^2.11.0
  google_generative_ai: ^0.4.7
  video_thumbnail: ^0.5.6
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon.png"
  adaptive_icon_background: "#F1F8E8"
  adaptive_icon_foreground: "assets/logo_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo_icon.png